services:
  - type: worker
    env: node
    name: cron-basic
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
